name: super_gra
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.9
  gradient_circular_progress_indicator: ^0.0.4
  rate_my_app: ^2.0.0
  url_launcher: ^6.2.4
  video_player: ^2.8.2
  flutter_local_notifications: ^16.3.2
  app_tracking_transparency: ^2.0.4

flutter_native_splash:
  color: "#1C1C27"
  image: assets/images/logo.png
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  fonts:
    - family: Codec Pro
      fonts:
        - asset: assets/fonts/CodecPro-Regular.ttf
        - asset: assets/fonts/CodecPro-Italic.ttf
          style: italic
